# Generated by Django 5.1.7 on 2026-02-05 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('LILA', 'Pastilla Lila'), ('NARANJA', 'Pastilla Naranja'), ('VERDE', 'Pastilla Verde')], max_length=10, unique=True, verbose_name='Color de Pastilla')),
                ('precio_actual', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Actual')),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pastilla',
                'verbose_name_plural': 'Pastillas',
                'ordering': ['-precio_actual'],
            },
        ),
    ]
